name: demo_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.2.1+1
  translator: ^1.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  open_filex: ^4.4.0
  file_picker: ^8.0.0
  webview_flutter: ^4.5.0
  get: 4.6.6
  url_launcher: ^6.3.0
  otp_autofill: ^3.0.2
  sms_autofill: ^2.4.0
  google_maps_flutter: ^2.9.0
  win32: ^5.5.4
  flutter_polyline_points: ^2.1.0
  map_location_picker: ^1.3.0
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.3.0

flutter:

  uses-material-design: true

  assets:
    - asset/map_style/