// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7iW4Edxp5omWuN82xy3w4qDuqJUb_1MU',
    appId: '1:100072656025:web:034b30496997ad154efc08',
    messagingSenderId: '100072656025',
    projectId: 'fir-firebase-463f5',
    authDomain: 'fir-firebase-463f5.firebaseapp.com',
    storageBucket: 'fir-firebase-463f5.appspot.com',
    measurementId: 'G-363T81DZVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJlYVL4skkqwWzydbEssi1ieo9X81fd1I',
    appId: '1:100072656025:android:484b1727a564c6c74efc08',
    messagingSenderId: '100072656025',
    projectId: 'fir-firebase-463f5',
    storageBucket: 'fir-firebase-463f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzRqgAJ87a4vCvnWc05XqAkor5qvy568',
    appId: '1:100072656025:ios:e4fd911605f305014efc08',
    messagingSenderId: '100072656025',
    projectId: 'fir-firebase-463f5',
    storageBucket: 'fir-firebase-463f5.appspot.com',
    iosBundleId: 'com.example.demoFirebase',
  );
}
